config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  devise_for :users

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeotuable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :events, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  # validates :name, presence: true, length: {maximum: 35}

  before_validation :set_name, on: :create

  after_commit :link_subscriptions, on: :create

  mount_uploader :avatar, AvatarUploader

  private

  def set_name
    self.name = "User №#{rand(0..100)}" if self.name.blank?
  end

  def link_subscriptions
    Subscription.where(user_id: nil, user_email: self.email).update_all(user_id: self.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_current_user, except: [:show]

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: I18n.t('controllers.users.updated')
    else
      render :edit
    end
  end

  private

    def set_current_user
      @user = current_user
    end

    def user_params
      params.require(:user).permit(:name, :email, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, html: { multipart: true }) do |f| %>
  <%= render partial: "partials/form_errors", locals: {model: @user} %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :avatar %>
    <p><%= image_tag(@user.avatar.thumb.url) if @user.avatar? %></p>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit t('views.buttons.save'), class: "btn btn-primary" %> || <%= link_to t('views.buttons.back'), :back %>
  </div>
<% end %>

app/views/users/_user.html.erb
<span class="user">
  <span class="user-avatar">
    <%= image_tag(user_avatar(user), class: 'img-icon') %>
  </span>
  <span class="user-name">
    <% if request.path == user_path(user) %>
      <%= user.name %>
    <% else %>
      <%= link_to user.name, user_path(user) %>
    <% end %>
  </span>
</span>

app/views/users/edit.html.erb
<h1><%= t('views.users.edit_profile') %></h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render "form" %>

    <p class="buffer-top">
      <%= link_to t('views.users.password_change'), edit_user_registration_path %>
    </p>
  </div>
</div>

app/views/users/show.html.erb
<div class="text-center">
  <h1><%= @user.name %></h1>

  <%= image_tag user_avatar(@user) %>

  <% if @user == current_user %>
    <p class="buffer-top">
      <%= link_to t('views.buttons.edit_profile'), edit_user_path(@user), class: "btn btn-default" %>
    </p>
  <% end %>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @user.events.any? %>
    <h3><%= t('views.users.organized') %></h3>
    <div class="row">
      <%= render partial: "events/event", collection: @user.events %>
    </div>
    <% else %>
    <p class="buffer-top"><%= t('views.users.no_event') %></p>
    <% end %>
  </div>
</div>