config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  devise_for :users

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :delete_all
  has_many :subscriptions, dependent: :delete_all
  has_many :subscribers, through: :subscriptions, source: :user, dependent: :delete_all
  has_many :photos, dependent: :delete_all

  validates :user, presence: true
  validates :title, presence: true, length: {maximum: 255}
  validates :address, presence: true
  validates :datetime, presence: true

  def visitors
    (subscribers + [user]).uniq
  end

  def pincode_valid?(pin2check)
    pincode == pin2check
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_event, only: [:show]
  before_action :set_current_user_event, only: [:edit, :update, :destroy]
  before_action :password_guard!, only: [:show]

  def index
    @events = Event.all
  end

  def show
    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])
  end

  def new
    @event = current_user.events.build
  end

  def edit
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to @event, notice: I18n.t('controllers.events.created')
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: I18n.t('controllers.events.updated')
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: I18n.t('controllers.events.destroyed')
  end

  private

    def password_guard!
      return true if @event.pincode.blank?
      return true if signed_in? && current_user == @event.user

      if params[:pincode].present? && @event.pincode_valid?(params[:pincode])
        cookies.permanent["events_#{@event.id}_pincode"] = params[:pincode]
      end

      unless @event.pincode_valid?(cookies.permanent["events_#{@event.id}_pincode"])
        flash.now[:alert] = I18n.t('controllers.events.wrong_pincode') if params[:pincode].present?
        render 'password_form'
      end
    end

    def set_event
      @event = Event.find(params[:id])
    end

    def set_current_user_event
      @event = current_user.events.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :address, :description, :datetime, :pincode)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="col-sm-6 col-md-6">
  <div class="thumbnail">
    <%= content_tag "div", ' ',
                                  class: "event-background",
                                  style: "background-image: url(#{asset_path("event_thumb.jpg")})"
    %>
    <div class="thumbnail-inner event-info-inner">
      <div class="caption">
        <div class="event-description">
          <h3><%= link_to event.title, event_path(event) %></h3>
          <h3><small><%= l(event.datetime, format: :short) %></small></h3>
          <div class="buffer-both"><%= event.address %></div>
        </div>

        <div>
          <% event.visitors.each do |user| %>
            <%= image_tag user_avatar_thumb(user), class: 'img-icon', title: user.name %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <%= render partial: "partials/form_errors", locals: {model: @event} %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :datetime %>
    <p><%= f.datetime_select :datetime, class: "form-control" %></p>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :pincode %>
    <%= f.text_field :pincode, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit t('views.buttons.save'), class: "btn btn-primary" %> ||
    <%= link_to t('views.buttons.back'), :back %>
  </div>
<% end %>

app/views/events/_subscription.html.erb
<div class="event-subscription-form">
  <h4><%= t('views.events.i_go') %></h4>
  <div>
    <%= render partial: 'subscriptions/form', locals: {subscription: @new_subscription || @event.subscriptions.build} %>
  </div>
</div>

app/views/events/edit.html.erb
<h1><%= t('views.events.edit_event') %></h1>

<%= render 'form' %>

app/views/events/index.html.erb
<h1><%= t('views.events.index_events') %></h1>

<div class="buffer-both">
  <%= link_to t('views.buttons.create_event'), new_event_path, class: "btn btn-success" %>
</div>

<div class="row buffer-bottom">
  <%= render partial: "events/event", collection: @events %>
</div>

app/views/events/new.html.erb
<h1><%= t('views.events.create_event') %></h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/events/password_form.html.erb
<h1><%= t('views.pincode.access') %></h1>

<%= form_tag('', method: :post) do |f| %>
  <div class="form-group">
    <%= label 'Пин-код', :pincode %>
    <%= text_field_tag :pincode, params[:pincode], class: 'form-control' %>
  </div>

  <div class="actions">
    <%= submit_tag t('views.pincode.enter'), class: "btn btn-primary" %> ||
    <%= link_to t('views.pincode.home'), events_path %>
  </div>
<% end %>

app/views/events/show.html.erb
<div class="event">
  <div class="event-info-row">
    <div class="col-md-12">
      <%= content_tag "div", " ",
                                    class: "event-background",
                                    style: "background-image: url(#{event_photo(@event)})"
      %>

      <div class="event-info-inner row">
        <div class="col-md-6">
          <div class="event-description">
            <h1><%= @event.title %></h1>
            <h3><%= l(@event.datetime, format: :short) %></h3>
            <h3>
              <small><%= @event.address %></small>
            </h3>
            <p><%= @event.description %></p>
          </div>

          <% if current_user_can_edit?(@event) %>
            <div class="buffer-both">
              <%= link_to t('views.change'), edit_event_path(@event), class: "btn btn-primary" %>
              <%= link_to t('views.delete'), event_path(@event),
                                                                method: :delete,
                                                                data: { confirm: t('views.destroy_confirm') },
                                                                class: 'btn btn-danger'
              %>
            </div>
          <% end %>
        </div>

        <div class="col-md-6">
          <div class="event-map" id="map" data-address="<%= @event.address %>"></div>
        </div>

      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <div class="event-photos">
        <div class="event-photos-gallery buffer-both">
          <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
        </div>

        <div class="buffer-both">
          <%= link_to t('views.photos.add'), '#', class: 'event-photo-form-link' %>
        </div>

        <div class="event-photo-form">
          <%= render partial: 'photos/form', locals: {photo: @new_photo || @event.photos.build} %>
        </div>
      </div>

      <div class="event-comments buffer-top">
        <%= render partial: 'comments/form', locals: {comment: @new_comment || @event.comments.build} %>

        <div class="buffer-both">
          <%= render partial: 'comments/comment', collection: @event.comments.except(@new_comment) %>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="event-owner buffer-both">
        <h4> <%= t('views.events.event_owner') %></h4>
        <%= render partial: 'users/user', object: @event.user %>
      </div>
      <div class="event-subscriptions">
        <h4><%= t('views.events.subscribers') %></h4>
        <div>
          <p>
            <%= render partial: 'subscriptions/subscription', collection: @event.subscriptions.except(@new_subscription) %>
          </p>
        </div>
      </div>

      <% unless current_user_can_edit?(@event) %>
        <%= render partial: 'events/subscription' %>
      <% end %>
    </div>
  </div>
</div>